#!/usr/bin/env bash
# shellcheck disable=SC2086
# show info about subdomains

fetch()
{
    domain="$1"
    subd="$2"
    dig "$subd.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subd"
}

for subd in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subd" ] ; then
	fetch "$1" "$subd"
    fi
done
