#!/usr/bin/env bash
# Install nginx

apt -y update ; apt -y upgrade ; apt-get -y install nginx

echo "http {
	sendfile on;
	tcp_nopush on;
	types_hash_max_size 2048;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	server {
	listen 80;
	server_name 54.236.24.25;

	location /base {
	return 200 'this is the base url';
}
}

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}
" > /etc/nginx/nginx.conf

nginx -s reload
service nginx restart
