#!/usr/bin/env bash
# installs nginx

apt-get -y update ; apt-get -y upgrade ; apt-get -y install nginx

ufw allow 'Nginx HTTP'

echo 'Hello World!' > /var/www/html/index.nginx-debian.html

service nginx restart
nginx -s reload
