#!/usr/bin/env bash
# Install nginx

apt -y update ; apt -y upgrade ; apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
ufw allow "Nginx HTTP"

echo "server {
    listen 80;
    server_name 54.236.24.25;
    location / {
        root /var/www/html;
        index index.html;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default


service nginx restart
