#!/usr/bin/env bash
# Install nginx

apt -y update ; apt -y upgrade ; apt-get -y install nginx

echo "
events {}

http {
    sendfile on;
    tcp_nopush on;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name 54.236.24.25;

	location /redirect_me {
         	  return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    	}
	location /xyz {
            return 404;
        }

        location /xyzfoo {
            return 404 'Ceci n\'est pas une page\n\n';
        }
    }

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
}
" > /etc/nginx/nginx.conf

service nginx restart
nginx -s reload
