#!/usr/bin/env bash
# HTTP header response
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=TR2HPSjcJ7I permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
service nginx start
