#!/usr/bin/env bash
# HTTP header response
apt-get -y update ; apt-get -y install nginx
ufw allow 'Nginx HTTP'

hostname=$(hostname)

echo "events {}
http {
    server {
        listen 80 default_server;
       
        location / {
            add_header X-Served-By $hostname;
        }
    }
}
" > /etc/nginx/nginx.conf;

service nginx restart
