#!/usr/bin/env bash
# install HAproxy load-balancer on ubuntu

sh -c 'echo "
frontend front
    bind *:80
    default_backend back
backend web-backend
   balance roundrobin
   server web1 52.86.221.178:80 check
   server web2 34.239.250.229:80 check
   " | sudo tee /etc/haproxy/haproxy.cfg'
service haproxy start
