#!/usr/bin/env bash
# all together

sigint_() {
    echo "Y U no love me?!"
}

term() {
    rm /var/run/myscript.pid
    exit
}

echo "$$" > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command" && term' SIGTERM
    trap 'sigint_' SIGINT
    trap 'term' SIGQUIT
done
