#!/usr/bin/env bash
# if 4 bad luck, if 8 good luck
c=1
while [ $c -le 10 ]; do
      if [ $c -eq 4 ];
      then
	  echo "bad luck"
      elif [ $c -eq 8 ];
      then
	  echo "good luck"
      else
	  echo "Best School"
      fi
      ((c += 1))
done
