#!/usr/bin/env bash
# print hours and minuts
hours=0
mins=1
while [ $hours -le 12 ]; do
      echo "Hour: $hours"
      while [ $mins -le 59 ]; do
      	    echo $mins
	    ((mins += 1))
      done
      ((mins=1))
      ((hours += 1))
done
