#!/usr/bin/env bash
# change localhost

cp /etc/hosts ~/hosts.new

sed -i "$ a\8.8.8.8 facebook.com" ~/hosts.new
sed -i "s/^127[0-9.]*\slocalhost/127.0.0.2 localhost/" ~/hosts.new

cp -f ~/hosts.new /etc/hosts
