#!/usr/bin/env bash
# run nginx as nginx

#sed -i '1s/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
#sed -i '/http {/a server { listen *:8080;}' /etc/nginx/nginx.conf
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf

if sudo nginx -t; then
    sudo service nginx reload
else
    echo "Nginx configuration test failed"
fi
